from fastapi import FastAPI
import os
from meme_generator import create_meme
from analyzer import load_trivy_report, analyze_logs
from discord_webhook import DiscordWebhook, DiscordEmbed

app = FastAPI()

# Discord Webhook URL (set in .env file)
DISCORD_WEBHOOK_URL = os.getenv("DISCORD_WEBHOOK_URL")

@app.post("/analyze_trivy_logs/")
async def analyze_trivy_logs():
    # Load the Trivy scan result (generated by GitHub Actions)
    trivy_report = load_trivy_report("trivy_output.json")

    # Analyze logs (you can customize this further)
    results = analyze_logs(trivy_report)

    # Generate meme based on vulnerability severity
    meme_path = create_meme(results['vuln_name'], results['severity'])

    # Send Discord notification with meme
    send_discord_notification(meme_path, results)

    return {"message": "Logs analyzed and meme created!"}

# Discord notification with meme
def send_discord_notification(meme_path, results):
    webhook = DiscordWebhook(url=DISCORD_WEBHOOK_URL)
    embed = DiscordEmbed(title="Vulnerability Alert!", description="Check out this vulnerability!", color=242424)
    embed.set_image(url=meme_path)
    embed.add_embed_field(name="Severity", value=results['severity'])
    embed.add_embed_field(name="Vulnerability", value=results['vuln_name'])
    webhook.add_embed(embed)
    webhook.execute()